"""
L0 State (Dashboard) of the agent itself.

Stores vital stats of the current process: ReAct loop metadata,
used LLM model, token costs, and short-term memory of thoughts
for injection into RAG. This information is embedded in the system context and allows
the agent to be aware of its configuration in real time.
"""

import time
from enum import Enum
from pydantic import BaseModel, Field
from src.utils.dtime import seconds_to_duration_str

from src import __version__


class AgentStatus(str, Enum):
    """Current status of the main agent's work."""

    IDLE = "idle"  # Waiting for the next tick (sleeping in Heartbeat)
    THINKING = (
        "thinking"  # Calculating prompt, forming request to LLM, or waiting for a response
    )
    ACTING = "acting"  # Executing tools (execute_skill)
    ERROR = "error"  # Fatal error in the loop


class AgentState(BaseModel):
    """
    Model representing the state of the current running agent process.
    """

    state: AgentStatus = AgentStatus.IDLE

    # LLM Settings
    llm_model: str = "unknown"
    temperature: float = 0.7

    # ReAct Loop
    current_step: int = 1  # Current reasoning step within a single wakeup
    max_react_steps: int = 15
    heartbeat_interval: int = 180

    # Current goal to maintain focus during long tasks (skill available at Meta interface level 0)
    current_goal: str = ""

    # System limits and modes
    continuous_cycle: bool = False
    proactive_guidance: bool = False

    context_high_ticks: int = 3
    context_medium_ticks: int = 7
    context_low_ticks: int = 15

    start_time: float = Field(default_factory=time.time)
    last_input_tokens: int = 0

    # Short-term memory
    last_thoughts: str = ""
    current_thoughts_tree: str = ""  # Stores Markdown thoughts tree generated by ToT

    last_action_args: list[str] = Field(default_factory=list)
    last_action_error: str = ""
    last_actions_result: str = ""  # Result of the last executed actions

    # Subconscious (Strict nested dictionary typing)
    subconscious_enabled: bool = False
    subconscious_counters: dict[str, dict[str, int]] = Field(default_factory=dict)

    def reset_step(self) -> None:
        """
        Resets the ReAct loop step and short-term memory.
        Called at the beginning of each new wakeup (tick).
        """
        
        self.current_step = 1
        self.last_thoughts = ""
        self.current_thoughts_tree = ""

        self.last_action_args.clear()
        self.last_action_error = ""
        self.last_actions_result = ""

    def update_state(self, new_state: AgentStatus) -> None:
        """
        Updates the agent's status (IDLE, THINKING, ACTING, ERROR).

        Args:
            new_state (AgentStatus): New status.
        """
        self.state = new_state

    def next_step(self) -> None:
        """
        Increments the step of the current ReAct loop.
        """

        self.current_step += 1

    def get_uptime(self) -> str:
        """
        Calculates the uptime (running time) of the current agent instance.

        Returns:
            str: Human-readable string format "DD days, HH:MM:SS".
        """
        return seconds_to_duration_str(time.time() - self.start_time)

    async def get_context_block(self, **kwargs) -> str:
        """
        Context provider.
        Returns a formatted Markdown block with agent and subconscious metadata for injection into the system prompt.

        Returns:
            str: Agent statistics, limits, system version, uptime, and subconscious state.
        """
        goal_str = f"\n* Current Goal: {self.current_goal}" if self.current_goal else ""

        base_info = f"""
### AGENT STATE
* JAWL Version: {__version__}
* Uptime: {self.get_uptime()}

* Heartbeat Interval: {self.heartbeat_interval}s
* Continuous Cycle: {self.continuous_cycle}
* Context Depth Ticks: High={self.context_high_ticks} | Medium={self.context_medium_ticks} | Low={self.context_low_ticks}

* LLM Model: {self.llm_model}
* Temperature: {self.temperature}

* ReAct Step: {self.current_step}/{self.max_react_steps}
* Input Tokens (current step): {self.last_input_tokens}

{goal_str}

        """.strip()

        # TODO: this block should probably be moved to the subconscious module, e.g. "get_context_block" and called from here
        if self.subconscious_enabled and self.subconscious_counters:
            subc_lines = [
                "\n\n### SUBCONSCIOUS STATE",
                "Cognitive background processes running parallel to the main ReAct loop. They automatically consolidate memory, adapt persona, and perform database cleanup.\n",
            ]

            descriptions = {
                "consolidation": "Automatic transfer of short-term operational experience (action and thought logs) into long-term semantic memory and structured links. Crystallizes extracted facts, rules, and knowledge, preventing amnesia.",
                "reflection": "Cognitive reappraisal of recent communications and interaction patterns. Updates CRM (Mental States) — modulates attitude toward external subjects, records new communication directives, and adapts character (Personality Traits).",
                "forgetting": "Information hygiene and irrelevant memory degradation. Scans vector and graph databases, purging corrupted data, duplicates, system noise, and error logs. Maintains high RAG semantic density, protecting context.",
            }

            for pattern_name, data in sorted(self.subconscious_counters.items()):
                current = data.get("current", 0)
                limit = data.get("limit", 0)
                desc = descriptions.get(pattern_name, "Background cognitive process.")

                display_name = pattern_name.capitalize()

                subc_lines.append(f"* {display_name}")
                subc_lines.append(f"  - until the next launch: {current}/{limit} ticks")
                subc_lines.append(f"  - description: {desc}")

            base_info += "\n".join(subc_lines)

        return base_info
