[pytest]
pythonpath = .

asyncio_mode = auto
asyncio_default_fixture_loop_scope = function

# Глушим вывод логгера в консоль при тестах (оставляем только ошибки)
log_cli = true
log_cli_level = ERROR

# Отключаем ворнинги от сторонних библиотек, чтобы не мусорили
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning