[pytest]
# Добавляем src в PYTHONPATH, чтобы импорты типа "from src.l00..." работали
pythonpath = .
asyncio_mode = auto
console_output_style = count
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning