identity:
  agent_name: AgentName

llm:
  model_name: model_name
  temperature: 0.7
  max_react_steps: 15

system:

  vector_db:
    similarity_threshold: 0.43
    embedding_model: "intfloat/multilingual-e5-small"
    
  # Интервал между циклами (в секундах)
  loop_interval_sec: 60

  context_depth:
    ticks: 20 # Tick у LLM = Наблюдение > Мысли > Действие > Результат