"""
Token Usage Tracker for Language Models.

Aggregates input and output token statistics for each ReAct cycle wakeup step.
Utilizes tiktoken for exact calculations where available, with a fallback heuristic
approximation for alternative and local models.
"""

import tiktoken
import logging
from collections import deque
from typing import Any, Dict, List

from src.utils.logger import main_logger


class TokenTracker:
    """
    Tracks and records language model token usage statistics.
    Maintains a rolling historical cache of processed tokens.
    """

    def __init__(self, maxlen: int = 100) -> None:
        """
        Initializes the tracker with a set history queue limit.

        Args:
            maxlen (int): Max number of rolling execution records to retain in memory.
        """

        self.input_history: deque[Dict[str, Any]] = deque(maxlen=maxlen)
        self.output_history: deque[Dict[str, Any]] = deque(maxlen=maxlen)

        self._current_tick_in = 0
        self._current_tick_out = 0

        try:
            self.encoding = tiktoken.get_encoding("o200k_base")
        except Exception:
            self.encoding = tiktoken.get_encoding("cl100k_base")

    def _approximate_tokens(self, text: str) -> int:
        """
        Calculates or approximates the token count of a given string.

        Args:
            text (str): String to evaluate.

        Returns:
            int: Calculated or estimated token count.
        """

        if not text:
            return 0
        try:
            return len(self.encoding.encode(text, disallowed_special=()))
        except Exception:
            return max(1, len(text) // 4)

    def count_messages_tokens(self, messages: List[Any]) -> int:
        """
        Aggregates and counts tokens across an array of OpenAI-formatted message objects.

        Args:
            messages (List[Any]): Array of message dicts.

        Returns:
            int: Sum of tokens across the entire message structure.
        """

        num_tokens = 0
        for message in messages:
            num_tokens += 5
            if isinstance(message, dict):
                m_dict = message
            elif hasattr(message, "model_dump"):
                m_dict = message.model_dump()
            else:
                m_dict = {"content": str(message)}

            for key, value in m_dict.items():
                if value is None:
                    continue
                if isinstance(value, str):
                    num_tokens += self._approximate_tokens(value)
                elif isinstance(value, list):
                    num_tokens += self._approximate_tokens(str(value))
        num_tokens += 3
        return num_tokens

    def add_input_record(
        self,
        messages: List[Any],
        log_prefix: str = "[LLM]",
        logger: logging.Logger = main_logger,
    ) -> int:
        """
        Records the token count consumed by system and user prompts.

        Args:
            messages (List[Any]): The input message list.
            log_prefix (str): Prefix string for the logger.
            logger (logging.Logger): Destination logger.

        Returns:
            int: The calculated input token count.
        """

        total_tokens = self.count_messages_tokens(messages)
        self.input_history.append({"total": total_tokens})

        self._current_tick_in += total_tokens

        logger.info(f"{log_prefix} Input tokens: {total_tokens}.")

        return total_tokens

    def add_output_record(
        self, output_text: str, log_prefix: str = "[LLM]", logger: logging.Logger = main_logger
    ) -> None:
        """
        Records the token count generated by the model response.

        Args:
            output_text (str): Raw string returned by the LLM.
            log_prefix (str): Prefix string for the logger.
            logger (logging.Logger): Destination logger.
        """

        output_tokens = self._approximate_tokens(output_text)
        self.output_history.append({"total": output_tokens})

        self._current_tick_out += output_tokens

        logger.info(f"{log_prefix} Output tokens: {output_tokens}.")
