name: JAWL Tests

# Запускать при пушах в ветки main/master и при создании Pull Request-ов
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование кода
      uses: actions/checkout@v4

    - name: Установка Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: "pip" # Ускоряет установку, кэшируя библиотеки

    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск автотестов
      # Указываем PYTHONPATH, чтобы pytest корректно видел папку src/
      env:
        PYTHONPATH: .
      run: |
        pytest -q tests/